### ISSUE TITLE
Make use of redis secret for actinia chart

### ISSUE THREAD

**Issue by mmacata** [mundialis/helm-charts#4]
Since 0.99.26 (allow redis config via environment variable #164 ), it is possible to specify the redis connection parametes not only as config value but also as environment variable. This could look like this in the statefulset:
```
        env:
        - name: REDIS_SERVER_PW
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.secretName }}
              key: {{ .Values.redis.secretKey }}
```
`REDIS_SERVER_URL`, `REDIS_SERVER_PORT` and `REDIS_SERVER_PW` can be set this way if needed.

This way, the open [TODO](https://github.com/mundialis/helm-charts/blob/main/charts/actinia/values.yaml#L124) can be dealt with.
